// import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import Providers from "./Providers";
import TaskUIProviders from "@/app/store/TaskUIProviders";
// import TableDataProvider from "./components/TableDataProvider";
// import TableDataProvider from "./components/TabkeDataProvider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Task Manager",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      // className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Toaster />
        <div>
          <TaskUIProviders>
            <Providers>{children}</Providers>
          </TaskUIProviders>
        </div>
      </body>
    </html>
  );
}
